@startuml actores

left to right direction
skinparam defaultFontName Arial
skinparam defaultFontSize 11

actor "Empleado"      as empleado
actor "Manager"       as manager
actor "RRHH"          as rrhh
actor "Administrador" as admin
actor "Visitante"     as visitante

empleado <|-- manager
manager  <|-- rrhh
rrhh     <|-- admin

@enduml
