@startuml casosUso

skinparam backgroundColor #FFFFFF

left to right direction
skinparam defaultFontName Arial
skinparam defaultFontSize 10

actor "Empleado" as empleado
actor "RRHH"     as rrhh

empleado <|-- rrhh

package "Sesión" {
  usecase "cerrarSesion()"     as UC_LOGOUT
  usecase "completarGestion()" as UC_CG
}

package "Parking" {
  usecase "abrirCalendarioParking()" as UC_ACP
  usecase "reservarPlaza()"          as UC_RP
  usecase "cancelarReservaParking()" as UC_CRP
  usecase "cederPlaza()"             as UC_CP
  usecase "cancelarCesion()"         as UC_CC
  usecase "configurarReglaCesion()"  as UC_CRC
  usecase "registrarVisitante()"     as UC_RV
  usecase "cancelarVisitante()"      as UC_CV
}

package "Oficinas" {
  usecase "abrirCalendarioOficinas()" as UC_ACO
  usecase "reservarPuesto()"          as UC_RPO
  usecase "cancelarReservaPuesto()"   as UC_CRPO
}

empleado --> UC_LOGOUT
empleado --> UC_CG
empleado --> UC_ACP
empleado --> UC_RP
(UC_CRP) <-- empleado
empleado --> UC_RV
(UC_CV) <-- empleado
(UC_ACO) <-- empleado
empleado --> UC_RPO
(UC_CRPO) <-- empleado

empleado --> UC_CP
empleado --> UC_CC
empleado --> UC_CRC

@enduml
