@startuml contexto

left to right direction
skinparam linetype polyline
skinparam defaultFontName Arial
skinparam defaultFontSize 10
skinparam stateBorderThickness 1.5
skinparam arrowThickness 1.2
skinparam arrowColor #444444

state "SESION_CERRADA" as SinAuth
state "SISTEMA_DISPONIBLE" as Menu

state "CALENDARIO_PARKING_ABIERTO" as CalParking
state "PLAZA_ABIERTA" as EditPlaza
state "CESION_ABIERTA" as EditCesion
state "VISITANTE_ABIERTO" as EditVisitante
state "CALENDARIO_OFICINAS_ABIERTO" as CalOficinas
state "PUESTO_ABIERTO" as EditPuesto
state "BANDEJA_SOLICITUDES_ABIERTA" as Bandeja
state "SOLICITUD_ABIERTA" as EditSolicitud
state "TABLON_ABIERTO" as Tablon
state "ANUNCIO_ABIERTO" as EditAnuncio
state "DIRECTORIO_ABIERTO" as Directorio
state "AJUSTES_ABIERTO" as Ajustes
state "PERFIL_ABIERTO" as EditPerfil
state "ADMINISTRACION_ABIERTA" as Admin
state "PANEL_ANALITICAS_ABIERTO" as Panel

[*] --> SinAuth

SinAuth --> Menu : iniciarSesion()

Menu --> SinAuth : cerrarSesion()
Menu --> CalParking   : abrirCalendarioParking()
Menu --> CalOficinas  : abrirCalendarioOficinas()
Menu --> Bandeja      : abrirBandejaSolicitudes()
Menu --> Tablon       : abrirTablon()
Menu --> Directorio   : abrirDirectorio()
Menu --> Ajustes      : abrirAjustes()
Menu --> Admin        : abrirAdministracion()
Menu --> Panel        : abrirPanelAnaliticas()

CalParking   --> EditPlaza      : reservarPlaza()
CalParking   --> EditCesion     : cederPlaza()
CalParking   --> EditVisitante  : registrarVisitante()
CalParking   --> CalParking     : cancelarReservaParking()
CalParking   --> CalParking     : cancelarCesion()
CalParking   --> CalParking     : cancelarVisitante()

EditPlaza      --> CalParking   : abrirCalendarioParking()
EditCesion     --> CalParking   : abrirCalendarioParking()
EditVisitante  --> CalParking   : abrirCalendarioParking()

CalOficinas  --> EditPuesto     : reservarPuesto()
CalOficinas  --> CalOficinas    : cancelarReservaPuesto()

EditPuesto    --> CalOficinas   : abrirCalendarioOficinas()

Bandeja      --> EditSolicitud  : solicitarAusencia()
Bandeja      --> EditSolicitud  : gestionarSolicitudAusencia()
Bandeja      --> EditSolicitud  : gestionarValidacionAusencia()
Bandeja      --> Bandeja        : cancelarSolicitudAusencia()

EditSolicitud --> Bandeja       : abrirBandejaSolicitudes()

Tablon       --> EditAnuncio    : publicarAnuncio()

EditAnuncio   --> Tablon        : abrirTablon()

Ajustes      --> EditPerfil     : editarPerfil()

EditPerfil    --> Ajustes       : abrirAjustes()

CalParking   --> Menu : completarGestion()
CalOficinas  --> Menu : completarGestion()
Bandeja      --> Menu : completarGestion()
Tablon       --> Menu : completarGestion()
Directorio   --> Menu : completarGestion()
Ajustes      --> Menu : completarGestion()
Admin        --> Menu : completarGestion()
Panel        --> Menu : completarGestion()

@enduml
